<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Producto extends Model
{
    protected $table ='productos';

    use SoftDeletes;

    protected $fillable = [
        'nombre',
        'descripcion',
        'precio',
        'unidad',
        'actividades_id',
        'users_id'
    ];
    protected $dates = ['deleted_at'];


    public function actividad(){
        return $this->hasOne('App\Actividad', 'actividades_id');
    }

    public static  function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        // it will automatically add authenticate user to created_by column of selected model 
        static::creating(function ($model){
            $model->users_id = auth()->user()->id;
        });

    }
}